-- CreateTable
CREATE TABLE `Garden` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(191) NOT NULL,
    `Location` VARCHAR(191) NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Plant` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `GardenId` INTEGER NOT NULL,
    `Name` VARCHAR(191) NOT NULL,
    `Species` VARCHAR(191) NULL,
    `PlantedDate` DATETIME(3) NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CareSchedule` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `PlantId` INTEGER NOT NULL,
    `Type` ENUM('WATERING', 'FERTILIZING') NOT NULL,
    `FrequencyDays` INTEGER NOT NULL,
    `LastDoneAt` DATETIME(3) NULL,
    `NextDueAt` DATETIME(3) NOT NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CareLog` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `PlantId` INTEGER NOT NULL,
    `ScheduleId` INTEGER NOT NULL,
    `Type` ENUM('WATERING', 'FERTILIZING') NOT NULL,
    `DoneAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `GrowthLog` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `PlantId` INTEGER NOT NULL,
    `PhotoUrl` VARCHAR(191) NOT NULL,
    `Note` VARCHAR(191) NULL,
    `Condition` ENUM('HEALTHY', 'WILTED', 'FLOWERING', 'FRUITING', 'DISEASED') NOT NULL,
    `LoggedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Plant` ADD CONSTRAINT `Plant_GardenId_fkey` FOREIGN KEY (`GardenId`) REFERENCES `Garden`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CareSchedule` ADD CONSTRAINT `CareSchedule_PlantId_fkey` FOREIGN KEY (`PlantId`) REFERENCES `Plant`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CareLog` ADD CONSTRAINT `CareLog_PlantId_fkey` FOREIGN KEY (`PlantId`) REFERENCES `Plant`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CareLog` ADD CONSTRAINT `CareLog_ScheduleId_fkey` FOREIGN KEY (`ScheduleId`) REFERENCES `CareSchedule`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `GrowthLog` ADD CONSTRAINT `GrowthLog_PlantId_fkey` FOREIGN KEY (`PlantId`) REFERENCES `Plant`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;
